apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: simple-api
  name: managed-api-controller-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: managed-api-controller-role-namespaced
subjects:
  - kind: ServiceAccount
    name: managed-api-controller-sa
    namespace: simple-api
