apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: simple-api
  name: managed-api-controller-role-namespaced
rules:

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [my-platfom.com]
    resources: [managed-apis]
    verbs: [list, watch, patch, get, delete]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [kopf.dev]
    resources: [kopfexamples]
    verbs: [list, watch]

  # Application: other resources it produces and manipulates.
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create, patch, get, list, watch]