apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-api-operator-deployment
  namespace: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managed-api-operator
  template:
    metadata:
      labels:
        app: managed-api-operator
    spec:
      serviceAccountName: managed-api-controller-sa
      containers:
      - name: operator
        image: benedektoth/managed-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
