apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managed-apis.my-platfom.com
spec:
  group: my-platfom.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                endpoint:
                  type: string
                payload:
                    type: object
                    properties:
                        name: 
                          type: string
                        version: 
                          type: string
                        release:
                          type: boolean                    

  scope: Namespaced
  names:
    plural: managed-apis
    singular: managed-api
    kind: ManagedApi
    shortNames:
      - mapi
